In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a                   #Inline command

array([1, 2, 3, 4, 5])

In [4]:
a[0], a[1], a[2]

(1, 2, 3)

## Advantages of NumPy
 - Take less memory
 - Fast
 - Convenient to use

In [5]:

import time
import sys

In [6]:
b = range(100)
print(sys.getsizeof(5)*len(b))

2800


In [7]:
c = np.arange(100)
print(c.size*c.itemsize)

400


In [21]:
size = 10000
l1 = range(size)
l2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)

In [65]:
start = time.time()
result = [(x+y) for x,y in zip(l1, l2)]
print("Python list took : ", (time.time() - start)*1000)
res = A1 + A2

Python list took :  1.9941329956054688


array([    0,     2,     4, ..., 19994, 19996, 19998])

### Basic operations

In [29]:
a = np.array([[1,2], [3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
# ndim gives the dimesions of numpy array
a.ndim

2

In [32]:
a.itemsize

4

In [33]:
a.shape

(3, 2)

In [35]:
a = np.array([[1,2], [3,4], [5,6]], dtype=np.float)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [36]:
a.itemsize

8

In [38]:
a = np.array([[1,2], [3,4], [5,6]], dtype=np.complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [40]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [43]:
print("Concatenation : ")
print(np.char.add(['hello', 'world'], ['Python', 'NumPy']))

Concatenation : 
['helloPython' 'worldNumPy']


In [46]:
print(np.char.multiply('hello ', 4))

hello hello hello hello 


In [48]:
print(np.char.center('hello', 20, fillchar='^'))

^^^^^^^hello^^^^^^^^


In [49]:
print(np.char.capitalize('how are you?'))

How are you?


In [50]:
print(np.char.lower(['WHO','WHAT']))

['who' 'what']


In [54]:
print(np.char.upper('python is easy'))

PYTHON IS EASY


In [58]:
print(np.char.split('Are you fine?'))
print(np.char.splitlines('Hello\nHow are you?'))

['Are', 'you', 'fine?']
['Hello', 'How are you?']


In [68]:
print(np.char.strip(['nina', 'admin', 'aman'], 'a'))

['nin' 'dmin' 'man']


In [61]:
print(np.char.join([':', '-'], ['DMY', 'YMD']))

['D:M:Y' 'Y-M-D']


In [63]:
print(np.char.replace('He is good coder', 'coder', 'writer'))

He is good writer
